### ISSUE TITLE
Encryption padding breaks Cross platform decryptions

### ISSUE THREAD

**Issue by codeuniquely** [wader/aes-arraybuffer#2]
Hi, 

There is a subtle bug when you encode and pad the last block and that bock falls exactly on a 16 byte boundary). inside crypto.js library.

I've been passing files to various other platforms and things like opensll and they have an issue decoding any file when it exactly a multiple of 16 bytes.

this can be resolved by padding the file with 16 bytes (of 0x10) and then the decryption works on all platforms.

the code change required is

```
function pkcs_pad_buffer_to_append(length) {

  var pad_byte_count = pkcs_max_pad_byte_count - (length % pkcs_max_pad_byte_count);
  if (pad_byte_count===0) {
    pad_byte_count = 16;
  }

  var pad_u8 = new Uint8Array(pad_byte_count);
  for (var i = 0; i < pad_byte_count; i++) {
    pad_u8[i] = pad_byte_count;
  }

  return pad_u8.buffer;
}
```

**Comment by wader** [comment]
Hello! hmm that is weird as i thought the code worked like that. Did some console fiddling:

``` Javascript
> for (var i = 0; i < 18; i++) console.log("length", i, "pad length", 16 - (i % 16))
length 0 pad length 16
length 1 pad length 15
length 2 pad length 14
length 3 pad length 13
length 4 pad length 12
length 5 pad length 11
length 6 pad length 10
length 7 pad length 9
length 8 pad length 8
length 9 pad length 7
length 10 pad length 6
length 11 pad length 5
length 12 pad length 4
length 13 pad length 3
length 14 pad length 2
length 15 pad length 1
length 16 pad length 16
length 17 pad length 15
```

`pad_byte_count` shouldn't even become zero. Can you give some hints on how to reproduce the issue with OpenSSL?

**Comment by codeuniquely** [comment]
Yes, my mistake,
When I consoled(out) the the value of value of pad_byte_count and was seeing a zero - didn't even stop to read the code and just wrote the inserted bit and didn't really read the bit above... 

The issue I was seeing when I encode a file that is exactly a multiple of 16 bytes long is that when you do you do a "openssl enc -d -aes-128-cbc -K xxxxx -iv yyyyy” on the encoded file, it throws a “bad decrypt” error at the very end of the file" 

So, find a binary file less than 1Mb but an exact multiple of 16 bytes) and encode it using openSSL passing in to hex keys key and iv"

```
openssl enc -aes-128-cbc -K 91C4905CBC172FBE863795FBF49924C8 -iv B7E338FB76BC557E4925126441F772C4 -in test.pdf -out output.bin
```

The use the library and read and encode the same file and save it to disc as output2.bin.

I then did a quick check in a Hex binary editor and looked at the end of the two files output1.bin and output2.bin and the last few bytes where different.   

All other file sizes work for me ...

**Comment by wader** [comment]
Tried to reproduce like this:

``` sh
$ echo -n 0123456789012345 > test
$ ls -l test
-rw-r--r--  1 mattias  staff  16 27 Maj 13:23 test
$ openssl enc -aes-128-cbc -K 00000000000000000000000000000000 -iv 00000000000000000000000000000000 -in test -out test.bin
$ xxd -i test.bin
unsigned char test_bin[] = {
  0x82, 0x21, 0xc5, 0xca, 0xb4, 0x04, 0x79, 0xa2, 0x81, 0xa4, 0x78, 0x8b,
  0x56, 0x0e, 0x67, 0xca, 0x79, 0x13, 0x32, 0xdb, 0x0b, 0xb8, 0x97, 0x6c,
  0x18, 0xf8, 0x3d, 0xa5, 0xd5, 0xed, 0x36, 0xf7
};
unsigned int test_bin_len = 32;
$ xxd -i test
unsigned char test[] = {
  0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31,
  0x32, 0x33, 0x34, 0x35
};
unsigned int test_len = 16;
```

Then in browser console:

``` javascript
> input = new Uint8Array([
  0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x30, 0x31,
  0x32, 0x33, 0x34, 0x35
]);
[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 48, 49, 50, 51, 52, 53]
> key = new Uint8Array(16);
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
> iv = new Uint8Array(16);
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
> encrypted = Crypto.encrypt_aes_cbc(Crypto.pkcs_pad(input.buffer), key.buffer, iv.buffer);
ArrayBuffer {}
> new Uint8Array(encrypted)
[130, 33, 197, 202, 180, 4, 121, 162, 129, 164, 120, 139, 86, 14, 103, 202, 121, 19, 50, 219, 11, 184, 151, 108, 24, 248, 61, 165, 213, 237, 54, 247]
// pasting test.bin bytes to compare
> [
  0x82, 0x21, 0xc5, 0xca, 0xb4, 0x04, 0x79, 0xa2, 0x81, 0xa4, 0x78, 0x8b,
  0x56, 0x0e, 0x67, 0xca, 0x79, 0x13, 0x32, 0xdb, 0x0b, 0xb8, 0x97, 0x6c,
  0x18, 0xf8, 0x3d, 0xa5, 0xd5, 0xed, 0x36, 0xf7
]
[130, 33, 197, 202, 180, 4, 121, 162, 129, 164, 120, 139, 86, 14, 103, 202, 121, 19, 50, 219, 11, 184, 151, 108, 24, 248, 61, 165, 213, 237, 54, 247]
```

Seems to produce the same binary as OpenSSL.

But really strange that it seems to work in non-aligned cases for you. Can you paste the encryption part of your code and maybe a test encrypted file that don't work?

**Comment by wader** [comment]
The only thing i can think of is if you pad after encrypt. Not sure how the js library will behave in that case, i would guess the "outside" bytes of the last non-aligned block will be treated as zero during encryption.

**Comment by codeuniquely** [comment]
Actually I've worked out what I'm doing wrong - I encode files in a series of chunks, each chunk is 1MB is size. Whilst I'm encoding the file I don't need to pad the bytes - I just need to pad the last chunk of bytes in the file.

I was basically checking for the last block of a file in in a really stupid way:

```
function encryptBytesToUint8Array(bytes, key, iv) {
  var input = new Uint8Array(bytes),
  buffer = (input.buffer.byteLength % 16 === 0) ? input.buffer : Crypto.pkcs_pad(input.buffer);

  var encrypted = Crypto.encrypt_aes_cbc(buffer, key.buffer, iv.buffer);
  return new Uint8Array(encrypted);
}
```

all my fault really ...

You can close this

**Comment by wader** [comment]
Aha ok, no problem! good luck with the project! what are you working on?

**Comment by codeuniquely** [comment]
Encoding Data files from Comms equipment before using upload to vendor (used to be Java Applet) - for all external customers of a global networks vendor.

**Comment by wader** [comment]
Nice :+1:
