### ISSUE TITLE
Портит файлы (It corrupts files). Размер файла перед шифрованием не совпадает после расшифровки в некоторых ситуациях.

### ISSUE THREAD

**Issue by Aertx0** [wader/aes-arraybuffer#3]
![default](https://cloud.githubusercontent.com/assets/28788745/26216057/6831ef32-3c0b-11e7-9170-2d9293d76856.png)
For english:
It corrupts files. The file size before encryption does not match after decryption in some situations.
Sample code: [stand.tar.gz](https://github.com/wader/aes-arraybuffer/files/1011818/stand.tar.gz)

**Comment by wader** [comment]
Hello, in `worker.js` change:
```
result['msg'] = Crypto.decrypt_aes_cbc(Crypto.pkcs_pad(event.data['msg']), key.buffer, iv.buffer);
```
To:
```
result['msg'] = Crypto.pkcs_unpad(Crypto.decrypt_aes_cbc(event.data['msg'], key.buffer, iv.buffer));
```
You need to unpad and unpadding should to be done on the decrypted data.

**Comment by Aertx0** [comment]
Thank you.

**Comment by wader** [comment]
No problem 👍
What are you working on?

**Comment by Aertx0** [comment]
My message https://privnote.com/EYUzyX2S#d5GzPa0bZ

**Comment by wader** [comment]
https://privnote.com/PptdczB7#OkY8HXpPk

**Comment by Aertx0** [comment]
https://privnote.com/ITfaxRVf#BnvB6ztVx

**Comment by Aertx0** [comment]
https://privnote.com/UozE62su#Sy9VmdGJ4

**Comment by wader** [comment]
https://privnote.com/9SmWiT45#00nF0slPR
